CREATE SCHEMA `pvdb` DEFAULT CHARACTER SET utf8mb4;
GRANT ALL PRIVILEGES ON pvdb.* TO 'pvuser'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON pvdb.* TO 'pvuser'@'localhost' IDENTIFIED BY '1234';
USE pvdb;